apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graylog-data
  namespace: graylog
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
