apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-logger
  labels:
    app: python-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-logger
  template:
    metadata:
      labels:
        app: python-logger
    spec:
      nodeSelector:
        kubernetes.io/hostname: raspberrypi
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "pi"
          effect: "NoSchedule"
      restartPolicy: Always
      containers:
        - name: app
          image: mrangelcruz1960/python-logger:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
              cpu: "100m"
          # readinessProbe:
          #   httpGet:
          #     path: /login
          #     port: 5000
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /metrics
          #     port: 5000
          #   initialDelaySeconds: 15
          #   periodSeconds: 20
