initContainers:
  - name: init-sysctl
    image: busybox:latest
    command:
      - sh
      - -c
      - |
        echo "Skipping sysctl init container"
    securityContext:
      privileged: true

